name: Generate Snake Contribution Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: SalmaSamyM
          outputs: |
            dist/github-contribution-grid-snake.svg
          color_snake: "#FF6EC7"
          color_dots: "#FFD700,#FF6EC7,#FF69B4,#800080"
          
      - name: Push snake animation to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
